version: '3.2'
services:
  # portal-client:
  #   build: '../packages/apisuite-client-portal'
  #   image: ${DOCKER_REPO}:${APISUITE_CLIENT_PORTAL_TAG}
  #   container_name: apisuite-client-portal-${APISUITE_ENVIRONMENT}
  #   restart: on-failure
  #   ports:
  #     - ${APISUITE_PORTAL_PORTS}
  # sandbox-client:
  #   build: '../packages/apisuite-client-sandbox'
  #   image: ${DOCKER_REPO}:${APISUITE_CLIENT_SANDBOX_TAG}
  #   container_name: apisuite-client-sandbox
  #   restart: on-failure
  #   ports:
  #     - "3001:8080"
  # marketplace-client:
  #   build: '../packages/apisuite-client-marketplace'
  #   image: ${DOCKER_REPO}:${APISUITE_CLIENT_MARKETPLACE_TAG}
  #   container_name: apisuite-client-marketplace-${APISUITE_ENVIRONMENT}
  #   restart: on-failure
  #   ports:
  #     - ${APISUITE_MARKETPLACE_PORTS}
  # sso-client:
  #   build: '../packages/apisuite-client-sso'
  #   image: ${DOCKER_REPO}:${APISUITE_CLIENT_SSO_TAG}
  #   container_name: apisuite-client-sso-${APISUITE_ENVIRONMENT}
  #   restart: on-failure
  #   ports:
  #     - ${APISUITE_SSO_PORTS}
  sandbox-client-dev:
    build: '../packages/apisuite-client-sandbox'
    image: ${DOCKER_REPO}:${APISUITE_CLIENT_SANDBOX_TAG}
    container_name: apisuite-client-sandbox-${APISUITE_ENVIRONMENT}
    restart: on-failure
    environment:
      - API_URL=${API_URL}
      - APP_URL=${APP_URL}
      - SUPPORT_URL=${SUPPORT_URL}
      - LOGIN_PORT=${LOGIN_PORT}
      - SIGNUP_ROUTE=${SIGNUP_ROUTE}
      - LOGIN_ROUTE=${LOGIN_ROUTE}
      - AUTH_ROUTE=${AUTH_ROUTE}
    ports:
      - ${APISUITE_SANDBOX_PORTS}
  # platform-client:
  #   build: '../packages/apisuite-platform'
  #   image: ${DOCKER_REPO}:${APISUITE_PLATFORM_TAG}
  #   container_name: apisuite-platform-${APISUITE_ENVIRONMENT}
  #   restart: on-failure
  #   ports:
  #     - ${APISUITE_PLATFORM_PORTS}
